console.log("🔍 AI 걸름이 작동 중");

const results = document.querySelectorAll('div.g');

results.forEach((result) => {
  const snippet = result.innerText.toLowerCase();

  const aiPatterns = [
    "as an ai language model",
    "in conclusion",
    "this article discusses",
    "ai can be helpful",
    "generated by",
    "chatgpt",
    "gpt-4",
    "bard",
    "claude"
  ];

  const isAI = aiPatterns.some(pattern => snippet.includes(pattern));

  if (isAI) {
    result.style.opacity = "0.3";

    const tag = document.createElement("div");
    tag.textContent = "🤖 [AI 의심 글]";
    tag.style.color = "red";
    tag.style.fontWeight = "bold";
    tag.style.marginBottom = "5px";
    result.prepend(tag);
  }
});
